### ISSUE TITLE
Can you please let me know, how to run the SOTA CODS model mentioned in the paper. 

### ISSUE THREAD

**Issue by shamanez** [salesforce/ConvSumm#3]
Amazing work. I read the paper and it says, CODS can actually control the number of sentences in the summary.   I think you have mentioned the generation pipeline under the topic of [CODS: Salesforce/cods-bart-large-xsum-samsum](https://github.com/salesforce/ConvSumm/tree/master/CODS#load-trained-model). 

I am interested in generating 1 sentence summaries. But I noticed sometimes, it does not generate TLDR, where it throws an error saying list out of index (due to this  **split(" TLDR ")[1]**).  Is there a specific reason to this? 

 When the number of words in conversation is less than the maximum output length (400), it says manually reduce the  max_length parameter.  Why are you using the parameter, 400 for this? Is it a hyperparameter? If I remove it will it generate dynamic length outputs?

**Comment by jasonwu0731** [comment]
@shamanez,

During training, we train the model to generate KEY_PHRASES TLDR SUMMARY, and during inference, if the KEY_PHRASES generated are longer than the max_length set, then we may see that error. One potential solution is you increase the max_length.

max_length is an inference hyperparameter that you can play with so the model will stop exploring until it reaches max_length. The warning you get is coming from huggingface library because it tries to remind you that your input is shorter than the output max_length summary. You can ignore that.

**Comment by shamanez** [comment]
Thanks.
